Branch zbiorczy
Miretpl/delta-1-backend pull request #26
Opened 2020-12-07 23:38 UTC by Doragu

W13 Przygotowanie endpointu archiwizacji -> usuwania karty
W15 Zmiana obsługi kolejności list i kart
W17 Przygotowanie endpointu archiwizacji -> usuwania listy

2020-12-08 12:36 UTC, MichalOgloza requested changes

2020-12-08 12:36 UTC, MichalOgloza commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +                    reorderCards(cardId, json.getInt("value"));
1. Podane dużej liczby jako orderNumber powoduje zmniejszenie wartości orderNumber pozostałych kart (pojawiają się wartości ujemne).
2. Jeśli zmieniam orderNumber, to numeracja jest aktualizowana dla wszystkich list, a nie tylko dla aktualnie modyfikowanej.

2020-12-08 12:36 UTC, MichalOgloza commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +            listCardsRepository.updateOrderNumberToLowerAfterDelete(listCards.getOrderNumber());
Ten sam problem co wyżej usuwanie aktualizuje kolejność na wszystkich listach nie tylko na tej do której należy usuwana karta.

2020-12-08 12:36 UTC, MichalOgloza commented on src/main/java/com/delta1/app/controller/ListEndpoints.java
> +                    reorderLists(listId, json.getInt("value"));
Ten sam problem co w kartach

2020-12-08 12:36 UTC, MichalOgloza commented on src/main/java/com/delta1/app/controller/ListEndpoints.java
> +            boardListsRepository.updateOrderNumberToLowerAfterDelete(boardLists.getOrderNumber());
Ten sam problem co w kartach

2020-12-08 19:19 UTC, Doragu commented on src/main/java/com/delta1/app/controller/ListEndpoints.java
> +            boardListsRepository.updateOrderNumberToLowerAfterDelete(boardLists.getOrderNumber());
Done

2020-12-08 19:19 UTC, Doragu commented on src/main/java/com/delta1/app/controller/ListEndpoints.java
> +                    reorderLists(listId, json.getInt("value"));
Done

2020-12-08 19:19 UTC, Doragu commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +            listCardsRepository.updateOrderNumberToLowerAfterDelete(listCards.getOrderNumber());
Done

2020-12-08 19:19 UTC, Doragu commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +                    reorderCards(cardId, json.getInt("value"));
Done

2020-12-08 19:19 UTC, Doragu commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +            Integer listId = json.getInt("listId");
Done

2020-12-08 21:45 UTC, MichalOgloza commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +            Integer listId = json.getInt("listId");
Jak na razie to łapiesz tylko NoSuchElementException który nie jest nigdzie rzucany.

2020-12-08 22:02 UTC, MichalOgloza commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +            listCardsRepository.updateOrderNumberToLowerAfterDelete(listCards.getOrderNumber());
ok

2020-12-08 22:02 UTC, MichalOgloza commented on src/main/java/com/delta1/app/controller/ListEndpoints.java
> +            boardListsRepository.updateOrderNumberToLowerAfterDelete(boardLists.getOrderNumber());
ok

2020-12-08 22:24 UTC, MichalOgloza commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +                    reorderCards(cardId, json.getInt("value"));
problem z punktu 1 nadal występuje, do obgadania na teams

2020-12-10 19:28 UTC, Doragu commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +            Integer listId = json.getInt("listId");
Done

2020-12-10 19:29 UTC, Doragu commented on src/main/java/com/delta1/app/controller/CardEndpoints.java
> +                    reorderCards(cardId, json.getInt("value"));
Done

2020-12-10 20:12 UTC, MichalOgloza approved these changes

2020-12-10 20:16 UTC, merged